spring:
  application:
    name: omdbTransformation
server:
  port: 8080
management:
  port: 8081
endpoints:
  enabled: true
  health:
    enabled: true
camel:
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /api/*
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.movie: DEBUG
    org.hibernate: ERROR
omdb:
 host: http://www.omdbapi.com
 api-key: 8b1dd361

      
        
        
        
        